-- Sample data for AllMyMeeples

INSERT INTO games (title, description, image_url, min_players, max_players, playtime_minutes, rating, categories, mechanics) VALUES
('Catan', 'Trade, build, and settle the island of Catan while competing for resources and victory points.', 
'/images/meeple-icon.png', 3, 4, 90, 4.2, ARRAY['Strategy', 'Family'], ARRAY['Trading', 'Dice Rolling', 'Route Building']),
('Ticket to Ride', 'Build train routes across the map to connect cities and complete destination tickets.', 
'/images/meeple-icon.png', 2, 5, 60, 4.4, ARRAY['Family', 'Strategy'], ARRAY['Set Collection', 'Route Building']),
('Codenames', 'Give clever one-word clues to help your team identify secret agents before the other team.',
 '/images/dice-icon.png', 2, 8, 15, 4.5, ARRAY['Party', 'Word Game'], ARRAY['Deduction', 'Team-Based Game']),
('Wingspan', 'Build an engine of birds in your wildlife preserve to score points through combos and habitats.',
 '/images/meeple-icon.png', 1, 5, 70, 4.7, ARRAY['Strategy', 'Animal'], ARRAY['Engine Building', 'Card Drafting', 'Set Collection']),
('Azul', 'Draft colorful tiles to decorate a palace wall while optimizing patterns and scoring points.',
 '/images/meeple-icon.png', 2, 4, 45, 4.6, ARRAY['Abstract', 'Family'], ARRAY['Tile Drafting', 'Pattern Building']),
('7 Wonders', 'Draft cards to build your civilization, develop resources, and construct a powerful wonder.',
 '/images/meeple-icon.png', 2, 7, 30, 4.5, ARRAY['Strategy', 'Card Game'], ARRAY['Card Drafting', 'Set Collection', 'Resource Management']),
('Carcassonne', 'Place tiles and followers to build cities, roads, and fields in a growing medieval landscape.',
 '/images/meeple-icon.png', 2, 5, 45, 4.4, ARRAY['Family', 'Strategy'], ARRAY['Tile Placement', 'Area Majority']),
('Pandemic', 'Work together as a team to stop global outbreaks and discover cures before time runs out.',
 '/images/resource-icon.png', 2, 4, 60, 4.6, ARRAY['Cooperative', 'Strategy'], ARRAY['Action Points', 'Hand Management', 'Set Collection']),
('Dominion', 'Build your deck of cards to create powerful combos and score the most victory points.',
 '/images/cards-icon.png', 2, 4, 30, 4.5, ARRAY['Card Game', 'Strategy'], ARRAY['Deck Building', 'Hand Management']),
('Terraforming Mars', 'Compete to develop Mars by raising temperature, oxygen, and oceans through strategic projects.',
 '/images/meeple-icon.png', 1, 5, 120, 4.8, ARRAY['Strategy', 'Science Fiction'], ARRAY['Engine Building', 'Card Drafting', 'Tile Placement']),
('Splendor', 'Collect gems and build a trade engine to attract nobles and gain prestige points.',
 '/images/meeple-icon.png', 2, 4, 30, 4.4, ARRAY['Family', 'Strategy'], ARRAY['Engine Building', 'Set Collection']),
('The Resistance', 'Deduce who among you are traitors in a tense social deduction game of missions and deception.',
 '/images/dice-icon.png', 5, 10, 30, 4.3, ARRAY['Party', 'Social Deduction'], ARRAY['Bluffing', 'Team-Based Game', 'Deduction']),
('Love Letter', 'Use deduction and risk-taking to deliver your letter to the princess before others do.',
 '/images/cards-icon.png', 2, 6, 20, 4.2, ARRAY['Card Game', 'Family'], ARRAY['Deduction', 'Hand Management', 'Player Elimination']),
('Root', 'Compete for control of a woodland kingdom with asymmetric factions and unique play styles.',
 '/images/meeple-icon.png', 2, 4, 90, 4.7, ARRAY['Strategy', 'Fantasy'], ARRAY['Area Control', 'Variable Player Powers', 'Card Crafting']),
('Gloomhaven', 'Embark on a campaign of tactical combat and story-driven adventures in a fantasy world.',
 '/images/meeple-icon.png', 1, 4, 120, 4.9, ARRAY['Strategy', 'Fantasy', 'Adventure'], ARRAY['Cooperative Play', 'Hand Management', 'Campaign']),
('Scythe', 'Lead your faction to victory through resource management, combat, and engine building.',
 '/images/meeple-icon.png', 1, 5, 115, 4.7, ARRAY['Strategy', 'Science Fiction'], ARRAY['Engine Building', 'Area Control', 'Resource Management']),
('Everdell', 'Build a woodland city with charming critters and constructions over changing seasons.',
 '/images/meeple-icon.png', 1, 4, 80, 4.6, ARRAY['Strategy', 'Fantasy'], ARRAY['Worker Placement', 'Tableau Building', 'Resource Management']),
('King of Tokyo', 'Roll dice and battle monsters to become the King of Tokyo through destruction and points.',
 '/images/meeple-icon.png', 2, 6, 30, 4.3, ARRAY['Family', 'Party'], ARRAY['Dice Rolling', 'Push Your Luck', 'Player Elimination']),
('Betrayal at House on the Hill', 'Explore a haunted mansion until one player betrays the group in a thrilling twist.',
 '/images/fighting-icon.png', 3, 6, 60, 4.2, ARRAY['Horror', 'Adventure'], ARRAY['Cooperative Play', 'Traitor Game', 'Tile Placement']),
('Exploding Kittens', 'Draw cards and avoid exploding kittens in this fast-paced, humorous card game.',
 '/images/cards-icon.png', 2, 5, 15, 4.1, ARRAY['Card Game', 'Party'], ARRAY['Push Your Luck', 'Hand Management', 'Player Elimination']),
('Dixit', 'Use imagination and storytelling to give clues and guess surreal illustrated cards.',
 '/images/dice-icon.png', 3, 6, 30, 4.5, ARRAY['Party', 'Family'], ARRAY['Storytelling', 'Deduction', 'Voting']),
('Uno', 'Match colors and numbers while trying to be the first to get rid of all your cards.',
 '/images/cards-icon.png', 2, 10, 20, 3.9, ARRAY['Card Game', 'Family'], ARRAY['Hand Management', 'Player Elimination']),
('Sushi Go!', 'Draft sushi cards to create the best meal combinations and score the most points.',
 '/images/cards-icon.png', 2, 5, 20, 4.3, ARRAY['Card Game', 'Family'], ARRAY['Card Drafting', 'Set Collection']),
('Risk', 'Conquer the world by controlling armies and territories in this classic strategy game.',
 '/images/meeple-icon.png', 2, 6, 120, 4.0, ARRAY['Strategy', 'War'], ARRAY['Area Control', 'Dice Rolling', 'Player Elimination']),
('Clue', 'Solve the mystery by deducing who committed the crime, with what weapon, and where.',
 '/images/meeple-icon.png', 2, 6, 45, 3.8, ARRAY['Family', 'Mystery'], ARRAY['Deduction', 'Roll and Move']),
('Spirit Island', 'Players work together as powerful spirits defending their island from invading colonizers.',
 '/images/meeple-icon.png', 1, 4, 120, 4.8, ARRAY['Strategy', 'Cooperative'], ARRAY['Area Control', 'Hand Management', 'Variable Player Powers']),
('Patchwork', 'Two players compete to build the best quilt by drafting oddly shaped patches.',
 '/images/meeple-icon.png', 2, 2, 30, 4.4, ARRAY['Abstract', 'Family'], ARRAY['Tile Placement', 'Time Track', 'Pattern Building']),
('Photosynthesis', 'Players grow trees and collect sunlight in a forest that changes with the moving sun.',
 '/images/meeple-icon.png', 2, 4, 60, 4.2, ARRAY['Strategy', 'Nature'], ARRAY['Area Control', 'Resource Management']),
('Small World', 'Fantasy races battle for control of a world that is too small for everyone.',
 '/images/meeple-icon.png', 2, 5, 80, 4.3, ARRAY['Strategy', 'Fantasy'], ARRAY['Area Control', 'Variable Player Powers']),
('Forbidden Island', 'A team of adventurers races to recover treasures and escape a sinking island.',
 '/images/resource-icon.png', 2, 4, 30, 4.1, ARRAY['Cooperative', 'Family'], ARRAY['Action Points', 'Set Collection', 'Grid Movement']),
('Jaipur', 'Two traders compete to earn the most wealth by buying, selling, and collecting goods.',
 '/images/cards-icon.png', 2, 2, 30, 4.5, ARRAY['Card Game', 'Strategy'], ARRAY['Set Collection', 'Hand Management']),
('The Crew: Mission Deep Sea', 'Players work together to complete tricky missions in a cooperative trick-taking game.',
 '/images/cards-icon.png', 2, 5, 20, 4.7, ARRAY['Card Game', 'Cooperative'], ARRAY['Trick Taking', 'Communication Limits']),
('Hanabi', 'Players cooperatively build fireworks displays while holding their cards backwards.',
 '/images/cards-icon.png', 2, 5, 25, 4.3, ARRAY['Card Game', 'Cooperative'], ARRAY['Deduction', 'Hand Management', 'Communication Limits']),
('Welcome To...', 'Players build a 1950s-style neighborhood by filling in house numbers and meeting objectives.',
 '/images/meeple-icon.png', 1, 6, 30, 4.2, ARRAY['Family', 'Strategy'], ARRAY['Flip and Write', 'Pattern Building']),
('Quacks of Quedlinburg', 'Players brew potions by drawing ingredients from a bag, pushing their luck for bigger scores.',
 '/images/meeple-icon.png', 2, 4, 45, 4.6, ARRAY['Family', 'Strategy'], ARRAY['Bag Building', 'Push Your Luck']),
('Tokaido', 'Travel across Japan, collecting experiences and enjoying the journey more than the destination.',
 '/images/meeple-icon.png', 2, 5, 45, 4.1, ARRAY['Family', 'Strategy'], ARRAY['Set Collection', 'Point to Point Movement']),
('Camel Up', 'Players bet on a chaotic camel race with stacked camels and surprising outcomes.',
 '/images/meeple-icon.png', 3, 8, 30, 4.3, ARRAY['Family', 'Party'], ARRAY['Betting', 'Dice Rolling']),
('Decrypto', 'Teams give coded clues while trying to understand their own code and intercept the other team''s.',
 '/images/dice-icon.png', 3, 8, 30, 4.5, ARRAY['Party', 'Word Game'], ARRAY['Deduction', 'Team-Based Game']),
('Skull', 'A bluffing game where players try to guess how many safe cards they can reveal.',
 '/images/dice-icon.png', 3, 6, 20, 4.2, ARRAY['Party', 'Card Game'], ARRAY['Bluffing', 'Deduction']),
('Mysterium', 'One player acts as a ghost giving visions, while others solve a murder mystery together.',
 '/images/resource-icon.png', 2, 7, 45, 4.3, ARRAY['Cooperative', 'Mystery'], ARRAY['Deduction', 'Hand Management', 'Cooperative Play']),
('Ark Nova', 'Players build modern zoos, manage conservation projects, and create powerful card combinations.',
 '/images/meeple-icon.png', 1, 4, 150, 4.9, ARRAY['Strategy', 'Animal'], ARRAY['Card Drafting', 'Engine Building', 'Action Selection']),
('Agricola', 'Farm, raise animals, and grow your household while managing scarce resources.',
 '/images/meeple-icon.png', 1, 4, 120, 4.7, ARRAY['Strategy', 'Farming'], ARRAY['Worker Placement', 'Resource Management']),
('Lords of Waterdeep', 'Compete as masked lords in the city of Waterdeep by recruiting adventurers and completing quests.',
 '/images/meeple-icon.png', 2, 5, 60, 4.4, ARRAY['Strategy', 'Fantasy'], ARRAY['Worker Placement', 'Secret Objectives']),
('Viticulture', 'Players run vineyards, plant grapes, and make wine to build the most successful winery.',
 '/images/meeple-icon.png', 1, 6, 90, 4.6, ARRAY['Strategy', 'Economic'], ARRAY['Worker Placement', 'Hand Management', 'Resource Management']),
('Sagrada', 'Draft colorful dice to build a stained glass window while following pattern restrictions.',
 '/images/meeple-icon.png', 1, 4, 45, 4.4, ARRAY['Family', 'Abstract'], ARRAY['Dice Drafting', 'Pattern Building']),
('Hive', 'A two-player abstract game where insect tiles are placed to surround the opponent''s queen bee.',
 '/images/meeple-icon.png', 2, 2, 20, 4.3, ARRAY['Abstract', 'Strategy'], ARRAY['Tile Placement', 'Grid Movement']),
('Cascadia', 'Build habitats and place wildlife tokens to create the most harmonious Pacific Northwest ecosystem.',
 '/images/meeple-icon.png', 1, 4, 45, 4.6, ARRAY['Family', 'Nature'], ARRAY['Tile Placement', 'Pattern Building', 'Set Collection']),
('Sea Salt & Paper', 'Create sea-themed combinations with cards and decide when to stop and score.',
 '/images/cards-icon.png', 2, 4, 30, 4.1, ARRAY['Card Game', 'Family'], ARRAY['Set Collection', 'Push Your Luck']),
('Railroad Ink', 'Roll dice and draw routes to connect highways and railways on your personal board.',
 '/images/meeple-icon.png', 1, 6, 30, 4.2, ARRAY['Family', 'Strategy'], ARRAY['Roll and Write', 'Route Building']),
('Dead of Winter', 'Survive a zombie apocalypse together while managing crises, morale, and possible betrayal.',
 '/images/resource-icon.png', 2, 5, 120, 4.3, ARRAY['Cooperative', 'Horror'], ARRAY['Worker Placement', 'Traitor Game', 'Hand Management']);

INSERT INTO users (email, password, name, role) VALUES
('admin@allmymeeples.com', '$2b$10$2ElLclzP2GkFCM7F.v23U.1KtNo482DGVNerajR41Q/DOwIhONH0i', 'Admin User', 'admin'),
('moderator@allmymeeples.com', '$2b$10$2ElLclzP2GkFCM7F.v23U.1KtNo482DGVNerajR41Q/DOwIhONH0i', 'Moderator User', 'moderator'),
('user@allmymeeples.com', '$2b$10$2ElLclzP2GkFCM7F.v23U.1KtNo482DGVNerajR41Q/DOwIhONH0i', 'Standard User', 'user')
ON CONFLICT (email) DO NOTHING;
